[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/weatherai/*"
  to = "https://api.weather-ai.co/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
